import sqlite3
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(
    page_title="NJ Pick3 Lab",
    page_icon="🎯",
    layout="wide"
)

ROOT = Path(__file__).resolve().parent
DB_FILE = ROOT / "database" / "pick3.db"
REPORTS_DIR = ROOT / "data" / "reports"

st.markdown("""
<style>
.main {
    background-color: #0f172a;
}
.block-container {
    padding-top: 1.5rem;
}
.big-title {
    font-size: 42px;
    font-weight: 800;
    color: #f8fafc;
}
.subtitle {
    color: #cbd5e1;
    font-size: 16px;
}
.warning-box {
    background: #451a03;
    color: #fed7aa;
    padding: 12px;
    border-radius: 12px;
    border: 1px solid #fb923c;
}
.card {
    background: linear-gradient(135deg, #1e293b, #0f172a);
    border: 1px solid #334155;
    border-radius: 18px;
    padding: 18px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.25);
}
.metric-label {
    color: #94a3b8;
    font-size: 14px;
}
.metric-value {
    color: #f8fafc;
    font-size: 30px;
    font-weight: 800;
}
</style>
""", unsafe_allow_html=True)


def read_excel(file_name, sheet_name):
    path = REPORTS_DIR / file_name
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_excel(path, sheet_name=sheet_name)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_draws():
    if not DB_FILE.exists():
        return pd.DataFrame()

    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql_query("""
        SELECT draw_date, draw_type, number, box
        FROM draws
        ORDER BY draw_date, draw_type
    """, conn)
    conn.close()

    df["draw_date"] = pd.to_datetime(df["draw_date"])
    df["year"] = df["draw_date"].dt.year
    df["month"] = df["draw_date"].dt.month_name()
    df["number"] = df["number"].astype(str).str.zfill(3)
    return df


def metric_card(label, value):
    st.markdown(
        f"""
        <div class="card">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
        </div>
        """,
        unsafe_allow_html=True
    )


draws = load_draws()

st.markdown('<div class="big-title">🎯 NJ Pick3 Lab</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Advanced Pick-3 analytics, scoring, rolling trends, skip tracking, and AI insights.</div>', unsafe_allow_html=True)
st.markdown("<br>", unsafe_allow_html=True)
st.markdown(
    '<div class="warning-box">Lottery outcomes are random. This dashboard shows historical patterns only — not guaranteed predictions.</div>',
    unsafe_allow_html=True
)

st.sidebar.title("🎛️ Controls")

if not draws.empty:
    years = sorted(draws["year"].unique())
    selected_years = st.sidebar.multiselect("Years", years, default=years)

    draw_types = sorted(draws["draw_type"].unique())
    selected_draws = st.sidebar.multiselect("Draw Type", draw_types, default=draw_types)

    filtered = draws[
        (draws["year"].isin(selected_years)) &
        (draws["draw_type"].isin(selected_draws))
    ]
else:
    filtered = draws

st.sidebar.divider()
st.sidebar.caption("Reports are generated by `python scripts/run_all.py`")

tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs([
    "🏠 Overview",
    "🏆 Master Picks",
    "🔥 Trend Candidates",
    "📊 Hot Signals",
    "⏳ Skip Tracker",
    "🤖 AI Analyst",
    "📁 Downloads"
])

with tab1:
    st.header("Dashboard Overview")

    if filtered.empty:
        st.error("No database data found. Make sure database/pick3.db exists.")
    else:
        c1, c2, c3, c4 = st.columns(4)

        with c1:
            metric_card("Total Draws", f"{len(filtered):,}")

        with c2:
            metric_card("First Draw", str(filtered["draw_date"].min().date()))

        with c3:
            metric_card("Latest Draw", str(filtered["draw_date"].max().date()))

        with c4:
            metric_card("Unique Boxes", filtered["box"].nunique())

        st.markdown("### Draws by Year")
        year_counts = filtered.groupby("year").size().reset_index(name="Draws")
        fig = px.bar(year_counts, x="year", y="Draws", text="Draws")
        st.plotly_chart(fig, use_container_width=True)

        st.markdown("### Recent Draws")
        st.dataframe(
            filtered.sort_values("draw_date", ascending=False).head(25),
            use_container_width=True,
            hide_index=True
        )

with tab2:
    st.header("🏆 Top Master Picks")

    master = read_excel("MASTER_FINAL_REPORT.xlsx", "Top_25_Master")

    if master.empty:
        st.error("MASTER_FINAL_REPORT.xlsx / Top_25_Master not found.")
    else:
        top_n = st.slider("Show top N", 5, min(100, len(master)), 25)

        st.dataframe(
            master.head(top_n),
            use_container_width=True,
            hide_index=True
        )

        if "Box" in master.columns and "Master Score" in master.columns:
            fig = px.bar(
                master.head(top_n),
                x="Box",
                y="Master Score",
                title="Top Master Scores",
                text="Master Score"
            )
            st.plotly_chart(fig, use_container_width=True)

with tab3:
    st.header("🔥 Trend-Based Candidate Picks")

    candidates = read_excel("MASTER_FINAL_REPORT.xlsx", "Top_25_Candidates")

    if candidates.empty:
        st.error("Candidate report not found.")
    else:
        st.dataframe(
            candidates,
            use_container_width=True,
            hide_index=True
        )

        if "Box" in candidates.columns and "Candidate Score" in candidates.columns:
            fig = px.bar(
                candidates.head(25),
                x="Box",
                y="Candidate Score",
                title="Top Trend Candidate Scores",
                text="Candidate Score"
            )
            st.plotly_chart(fig, use_container_width=True)

with tab4:
    st.header("📊 Hot Signals")

    digits = read_excel("MASTER_FINAL_REPORT.xlsx", "Hot_Digits")
    pairs = read_excel("MASTER_FINAL_REPORT.xlsx", "Hot_Pairs")
    sums = read_excel("MASTER_FINAL_REPORT.xlsx", "Hot_Sums")

    c1, c2, c3 = st.columns(3)

    with c1:
        st.subheader("Hot Digits")
        st.dataframe(digits.head(10), use_container_width=True, hide_index=True)
        if not digits.empty:
            fig = px.bar(digits.head(10), x=digits.columns[0], y=digits.columns[1])
            st.plotly_chart(fig, use_container_width=True)

    with c2:
        st.subheader("Hot Pairs")
        st.dataframe(pairs.head(10), use_container_width=True, hide_index=True)
        if not pairs.empty:
            fig = px.bar(pairs.head(10), x=pairs.columns[0], y=pairs.columns[1])
            st.plotly_chart(fig, use_container_width=True)

    with c3:
        st.subheader("Hot Sums")
        st.dataframe(sums.head(10), use_container_width=True, hide_index=True)
        if not sums.empty:
            fig = px.bar(sums.head(10), x=sums.columns[0], y=sums.columns[1])
            st.plotly_chart(fig, use_container_width=True)

with tab5:
    st.header("⏳ Skip Tracker")

    skip = read_excel("MASTER_FINAL_REPORT.xlsx", "Skip_Tracker")

    if skip.empty:
        st.error("Skip tracker not found.")
    else:
        min_hits = st.slider("Minimum historical hits", 1, 10, 3)

        if "Hits" in skip.columns:
            skip_filtered = skip[skip["Hits"] >= min_hits]
        else:
            skip_filtered = skip

        st.dataframe(
            skip_filtered.head(75),
            use_container_width=True,
            hide_index=True
        )

        if "Box" in skip_filtered.columns and "Current Skip" in skip_filtered.columns:
            fig = px.bar(
                skip_filtered.head(25),
                x="Box",
                y="Current Skip",
                title="Most Overdue Boxes"
            )
            st.plotly_chart(fig, use_container_width=True)

with tab6:
    st.header("🤖 Groq AI Analyst")

    ai_file = REPORTS_DIR / "PHASE_13_GROQ_AI_ANALYSIS.txt"

    if ai_file.exists():
        st.markdown(ai_file.read_text(encoding="utf-8"))
    else:
        st.error("AI analysis file not found. Run pipeline first.")

with tab7:
    st.header("📁 Report Downloads")

    if REPORTS_DIR.exists():
        files = sorted(REPORTS_DIR.glob("*"))

        for file in files:
            with open(file, "rb") as f:
                st.download_button(
                    label=f"Download {file.name}",
                    data=f,
                    file_name=file.name
                )
    else:
        st.error("Reports folder not found.")